### ISSUE TITLE
Velero Backup Status Stuck in `InProgress` Phase

### ISSUE THREAD

**Issue by ugur99** [vmware-tanzu/velero#4904]
**What steps did you take and what happened:**

Velero backups, whether scheduled or manually triggered, sometimes get stuck in the `in progress` phase (that's why the next scheduled ones are get stuck in `new` phase). When I ran `velero backup describe <backup-name>` I realized that the values of `Estimated total items to be backed up:` and `Items backed up so far:` are different, but I can not detect which resources could not been backed up. Even though waiting for a long time, the process is not completed.

**What did you expect to happen:**

* Velero should backup all manifests and volumes.
* Velero logs should clearly point out that which resources could not been backed up and the reason of it.
* If in somehow there is a stuck backup process and if it is a known issue, then velero should work in parallel processes or delete stuck one to continue to backup.

**The following information will help us better understand what's going on**:

- [`kubectl logs deployment/velero -n velero`](https://gist.githubusercontent.com/ugur99/3d9645f54ead6f62ca84d4247ca047b4/raw/853e56f53f8f2f61eed52eb1e820ef82060e8ead/velero.log)
- [`velero backup describe <failed-one>` or `kubectl get backup/<failed-one> -n velero -o yaml`](https://gist.github.com/ugur99/0bae7691ec488a123ddeb02b6f0e8fa4)
- [`velero backup describe <successful-one>` or `kubectl get backup/<successful-one> -n velero -o yaml`](https://gist.github.com/ugur99/13b244324e97147d2431ab4adae5e1c1)
- [`values.yaml`](https://gist.github.com/ugur99/ead355b9e2bd16064fbc6adf1240a692)

**Anything else you would like to add:**
In velero logs we could not find something to differentiate; we think that error logs related with 'missing region in aws configuration' ones are not crucial because we also got it when successful backups in the case; I guess we get this error since we are using minio. Could it be a bug that we are hitting in this version of velero? We'll appreciate any ideas to troubleshoot this case or any workaround of it. Thank you.

**Environment:**

- Velero helm chart version: 2.29.4
- Velero version (use `velero version`): 
Client:
	Version: v1.7.0
	Git commit: -
Server:
	Version: v1.8.1
- Velero features (use `velero client config get features`): 
features: <NOT SET>
- Kubernetes version (use `kubectl version`): v1.21.5
- Kubernetes installer & version: kubecspray v2.17.0
- Cloud provider or hardware configuration: Onprem
- OS (e.g. from `/etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by chrislinan** [comment]
Hi @ugur99 , Is your velero pod restart in the backup process? If so, the backup will stuck in the status `in process` forever.

**Comment by blackpiglet** [comment]
@ugur99 
First, as @chrislinan said, please check whether there is a Velero pod restart in backup progress.
Second, I found CSI plugin is enabled. Does your on-premise environment provides any CSI driver that supports snapshotting? If not, please use Restic instead to do the PV backup/restore.

**Comment by ugur99** [comment]
Thanks for your quick responses @chrislinan and @blackpiglet. 

I forgot to mention about our storage solution; sorry for that. We are using `rook` and `ceph`, we installed ceph cluster on some worker nodes. And we are using `ceph-rbd` and `cephfs csi drivers`. In our case all volumes are Ceph RBD CSI backed ones, there are exactly 15 many persistent volumes like this. We also attached our volumeSnapshotClassess `ceph-block` and `ceph-filesystem` with `velero.io/csi-volumesnapshot-class=true` key/value pair. We deployed `snapshot-controller` in kube-system namespace and it watches the new `volumesnapshots`; and when it sees a new vs created by velero; it manages the snapshot process. Thats the our solution and backup/restore process has been working until upgrade velero from `1.6.2` to `1.8.1` version (we upgraded to handle with garbage objects of ttl expired backups and it works as expected). Now we experience sometimes stuck backup processes. By the way we have one more cluster using the same backup solution for csi-backed volumes; but we have never experienced such an issue on that cluster.

We've never seen any restart of velero pod. We also monitor the resource usage of it, and we see a sharp increase of cpu usage from 5m-10m to 250m while taking a backup. Memory usage is usually about 45Mib, and it rises to 100Mib when taking backup process. Both of these values are under the our request/limit thresholds.

Although I open debug mode, I can't see any errors or a differentiative logs in the time range it is stuck. I am sharing some additional contents from the last stuck backup case:

![velero-backup-get](https://user-images.githubusercontent.com/57688057/167785296-a76f3eaa-54b0-468b-8933-44ff2cc51996.png)

![velero-pod-memory-usage](https://user-images.githubusercontent.com/57688057/167783543-7068f49e-0fe3-4f98-b403-fc18ef7a07e0.png)

![velero-pod-cpu-usage](https://user-images.githubusercontent.com/57688057/167783664-d0f3f587-bb9c-47d1-b870-0c8b25bd3fd8.png)

As you can see, all vs are in ready status; they are all belong to the stuck backup.
![vs-status](https://user-images.githubusercontent.com/57688057/167784718-cab22c2b-992e-434d-8094-f4de5820fb5f.png)

Since I could not get the logs of this case due to the log retention time of container; I triggered a new backup with the name `betav8` and it also stuck with the same way; and I uptaded/added the [`kubectl logs deployment/velero -n velero`](https://gist.github.com/ugur99/3d9645f54ead6f62ca84d4247ca047b4#file-velero-betav8-debug-log)

If you need further info please let me know. Thank you for your support.

**Comment by blackpiglet** [comment]
@ugur99 

#4863 This is a similar issue to your case. There is already a fix in Velero main release.
Could you try with main Velero image again?

**Comment by blackpiglet** [comment]
@ugur99 
The VolumeSnapshots deletion after backup is expected in Velero v1.9. Because VolumeSnapshots are namespaced resource. There are some cases deleting the namespace that VolumeSnapshots are in, then the snapshots on cloud are deleted (VolumeSnapshotClass's DeletionPolicy set to Delete), or only VolumeSnapshotContent are left (VolumeSnapshotClass's DeletionPolicy set to Retain), which let the csi-snapshotter cannot handling snapshot cleaning on cloud when backup is deleted.
Please help to check whether backup and restore works fine after this change.

For the consecutive backup created from schedule, could you please check the schedule's setting? It looks like that the schedule to set run every minute, so a new backup is created right after the old one completed.

**Comment by ugur99** [comment]
Thanks for the update @blackpiglet.

There is no problem to backup/restore for backups manually triggered ones. However we have problem with the `scheduled ones`: consecutive non-stop backups as I mentioned before. I checked definitions for `schedules.velero.io` crd and it is scheduled to backup every one hour. 

<img width="1787" alt="Screen Shot 2022-05-13 at 14 10 13" src="https://user-images.githubusercontent.com/57688057/168286820-330d971e-d9e1-4707-8aa0-55163ddf8a5a.png">

So it should backup once every hour but many backups have triggered consecutively; also number of them increase over time and never stop. 

<img width="1503" alt="Screen Shot 2022-05-13 at 14 09 34" src="https://user-images.githubusercontent.com/57688057/168287755-45ec53da-c70b-4829-814a-0bd1ebf7b418.png">

I checked velero logs; I did not see any error/warning in the logs that could cause this behavior. I am sharing the logs with you; maybe it makes sense to you.

[`kubectl logs deployment/velero -n velero`](https://gist.githubusercontent.com/ugur99/3d9645f54ead6f62ca84d4247ca047b4/raw/ac35df72d0a72a8d041df76a85ab50601c03701c/velero-last.log)

Again thanks you for your support.

**Comment by blackpiglet** [comment]
@ywk253100 
Looks like there is some corner case which will cause Schedule controller to constantly creating backup even the backup was created minute ago.

I found the update schedule's LastBackup time failure log, but still not sure why cannot find the schedule triggered the reconcile.
``` bash
time="2022-05-13T11:05:03Z" level=error msg="Reconciler error" error="error running submitBackupIfDue for schedule velero/velero-dantics-k8s-as-scheduled-cluster-backup: error updating Schedule's LastBackup time to 2022-05-13 11:05:03.559121013 +0000 UTC m=+1271.431182938: schedules.velero.io \"velero-dantics-k8s-as-scheduled-cluster-backup\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/schedule_controller.go:210" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*scheduleReconciler).submitBackupIfDue" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121"
```

**Comment by ywk253100** [comment]
@blackpiglet  The not found error should be caused by the outdated CRDs.

The CRDs on helm chart aren't updated yet, so you can't just replace the image

**Comment by blackpiglet** [comment]
@ywk253100 Thanks for input.

@ugur99 
According to Wenkai, CRD in cluster version mismatch with Velero controller in image version.
I think this is caused by upgrade Velero images to main, but CRD is not upgraded accordingly. You find the update-to-date CRD in https://github.com/vmware-tanzu/velero/tree/main/config/crd/v1/bases

Thanks for your cooperation. Velero v1.9 is planning to RC in two weeks. There is going to a official way of installing up-to-date Velero after that.

**Comment by ugur99** [comment]
That's great news; we are looking forward to new release! I am closing the issue. 

Thanks for your help @blackpiglet @ywk253100.
